### ISSUE TITLE
Evaluate the Euroc dataset

### ISSUE THREAD

**Issue by xenia-Y** [UZ-SLAMLab/ORB_SLAM3#558]
When I try to evaluate the Euroc dataset, this error raised up. 
I know it might be because of the python3 and python2 version problems, but I don't know how to fix it.
The error message is in the following.
ruihong@ruihong-Legion-7-16ACHg6:~/code/ORB_SLAM3$ python3 evaluation/evaluate_ate_scale.py evaluation/Ground_truth/EuRoC_left_cam/MH04_GT.txt f_dataset-MH04_stereo.txt --plot MH04_stereo.pdf
0.100936,1.010031,0.074809
Traceback (most recent call last):
  File "evaluation/evaluate_ate_scale.py", line 217, in <module>
    plot_traj(ax,first_stamps,first_xyz_full.transpose().A,'-',"black","ground truth")
  File "evaluation/evaluate_ate_scale.py", line 116, in plot_traj
    interval = numpy.median([s-t for s,t in zip(stamps[1:],stamps[:-1])])
TypeError: 'dict_keys' object is not subscriptable

**Comment by HJMGARMIN** [comment]
python2
