### ISSUE TITLE
ORB_SLAM3::System issues during initialization

### ISSUE THREAD

**Issue by morrsgarage** [UZ-SLAMLab/ORB_SLAM3#630]
Hey folks,

I'm trying to use the orb slam 3 interface to obtain positions in space, i don't have a camera physically connected, instead i pass the frames and the imu to  System::TraceRGBD and essentially obtain the information in runtime.

anyway so i am using LMWAFER docker image, the examples are working just fine but w/e i attempt to invoke this code:

   ORB_SLAM3::System SLAM(argv[1],argv[2],ORB_SLAM3::System::IMU_RGBD, true, 0,
                           "/dpds/ORB_SLAM3/Examples/Tevel/slam-core/config/RealSense_D435i.yaml");

with 

dpds/ORB_SLAM3/build/bin/tevel_slam /dpds/ORB_SLAM3/Vocabulary/ORBvoc.txt /dpds/ORB_SLAM3/Examples/Tevel/slam-core/config/RealSense_D435i.yaml

the error:
`ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: RGB-D-Inertial
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.6.0-dev) /dpds/opencv/modules/core/src/persistence.cpp:692: error: (-5:Bad argument) Input file is invalid in function 'open'

Aborted (core dumped)

please help
`

**Comment by morrsgarage** [comment]
please help :CCC

**Comment by morrsgarage** [comment]
i managed to pass that:

root@r131-far-7b76474d46-xbcgl:/dpds/ORB_SLAM3/build/bin# ./tevel_slam ORBvoc.txt RealSense_D435i.yaml 
2022/08/15 15:59:08.664750 [INFO] timeUtility::getCurrentMicro() USE ROS IS SET TO FALSE
2022/08/15 15:59:08.664795 [TRACE] GrpcAbstractDriver::GrpcAbstractDriver()
2022/08/15 15:59:08.664801 [TRACE] GrpcAbstractDriver::setThresholdToPrint(), sendingThreshold=80, grabbingThreshold=50
2022/08/15 15:59:08.665355 [INFO] FrontCameraDataInterface::FrontCameraDataInterface(), GOT DNS FROM ENVIRONMENT VARIABLE, [r131-front-camera-driver], IP=10.43.170.209
2022/08/15 15:59:08.665362 [INFO] FrontCameraDataInterface::FrontCameraDataInterface(), GOT PORT FROM ENVIRONMENT VARIABLE 3500
2022/08/15 15:59:08.665381 [TRACE] sharedMemoryHandler::sharedMemoryHandler(), UNIQUE IDENTIFIER- r131_frontCameraDriver, SIZE- 24, OWNER- false
2022/08/15 15:59:08.665389 [TRACE] sharedMemoryHandler::reInitSharedMemorySize(), UNIQUE IDENTIFIER- r131_frontCameraDriver, RESIZING TO=4301468
2022/08/15 15:59:08.665398 [TRACE] doubleBufferSMHandler::initAsSlave(), r131_frontCameraDriver, SUCCESSFULLY
2022/08/15 15:59:08.665942 [TRACE] sharedMemoryHandler::sharedMemoryHandler(), UNIQUE IDENTIFIER- r131_D435_GYRO, SIZE- 24, OWNER- false
2022/08/15 15:59:08.665947 [TRACE] sharedMemoryHandler::reInitSharedMemorySize(), UNIQUE IDENTIFIER- r131_D435_GYRO, RESIZING TO=238
2022/08/15 15:59:08.665952 [TRACE] doubleBufferSMHandler::initAsSlave(), r131_D435_GYRO, SUCCESSFULLY
2022/08/15 15:59:08.665957 [TRACE] sharedMemoryHandler::sharedMemoryHandler(), UNIQUE IDENTIFIER- r131_D435_ACCL, SIZE- 24, OWNER- false
2022/08/15 15:59:08.665960 [TRACE] sharedMemoryHandler::reInitSharedMemorySize(), UNIQUE IDENTIFIER- r131_D435_ACCL, RESIZING TO=238
2022/08/15 15:59:08.665965 [TRACE] doubleBufferSMHandler::initAsSlave(), r131_D435_ACCL, SUCCESSFULLY
ORBvoc.txt
RealSense_D435i.yaml

ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: RGB-D-Inertial
Loading settings from RealSense_D435i.yaml
Camera1.k3 optional parameter does not exist...
        -Loaded camera 1
Camera.newHeight optional parameter does not exist...
Camera.newWidth optional parameter does not exist...
        -Loaded image info
        -Loaded IMU calibration
        -Loaded RGB-D calibration
        -Loaded ORB settings
Viewer.imageViewScale optional parameter does not exist...
        -Loaded viewer settings
System.LoadAtlasFromFile optional parameter does not exist...
System.SaveAtlasToFile optional parameter does not exist...
        -Loaded Atlas settings
System.thFarPoints optional parameter does not exist...
        -Loaded misc parameters
----------------------------------
SLAM settings: 
        -Camera 1 parameters (Pinhole): [ 617.201 617.362 324.637 242.462 ]
        -Camera 1 distortion parameters: [  0 0 0 0 ]
        -Original image size: [ 640 , 480 ]
        -Current image size: [ 640 , 480 ]
        -Sequence FPS: 30
        -Gyro noise: 0.01
        -Accelerometer noise: 0.1
        -Gyro walk: 1e-06
        -Accelerometer walk: 0.0001
        -IMU frequency: 200
        -RGB-D depth map factor: 1000
        -Features per image: 1250
        -ORB scale factor: 1.2
        -ORB number of scales: 8
        -Initial FAST threshold: 20
        -Min FAST threshold: 7


Loading ORB Vocabulary. This could take a while...
Illegal instruction (core dumped)


now stuck on orb vocublary loading...

**Comment by morrsgarage** [comment]
Starting program: /dpds/ORB_SLAM3/Examples/RGB-D-Inertial/rgbd_inertial_realsense_D435i /dpds/ORB_SLAM3/Vocabulary/ORBvoc.txt /dpds/ORB_SLAM3/Examples/RGB-D-Inertial/RealSense_D435i.yaml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe7c53700 (LWP 1378)]
[New Thread 0x7fffe7452700 (LWP 1379)]
[New Thread 0x7fffe6c51700 (LWP 1380)]
[New Thread 0x7fffe6c51700 (LWP 1381)]
[Thread 0x7fffe6c51700 (LWP 1380) exited]
[Thread 0x7fffe6c51700 (LWP 1381) exited]
[New Thread 0x7fffe6c51700 (LWP 1382)]
[New Thread 0x7fffe6450700 (LWP 1383)]
[New Thread 0x7fffe5c4f700 (LWP 1384)]

[New Thread 0x7fffe544e700 (LWP 1385)]
[New Thread 0x7fffe4c4d700 (LWP 1386)]
[New Thread 0x7fffe444c700 (LWP 1387)]
[New Thread 0x7fffe3c4b700 (LWP 1388)]
[New Thread 0x7fffe344a700 (LWP 1389)]
Sensor supports the following options:

  0: Backlight Compensation is not supported
  1: Brightness is not supported
  2: Contrast is not supported
  3: Exposure
       Description   : Depth Exposure (usec)
       Current Value : 8500
  4: Gain
       Description   : UVC image gain
       Current Value : 16
  5: Gamma is not supported
  6: Hue is not supported
  7: Saturation is not supported
  8: Sharpness is not supported
  9: White Balance is not supported
  10: Enable Auto Exposure
       Description   : Enable Auto Exposure
       Current Value : 1
  11: Enable Auto White Balance is not supported
  12: Visual Preset
       Description   : Advanced-Mode Preset
       Current Value : 0
  13: Laser Power
       Description   : Manual laser power in mw. applicable only when laser power mode is set to Manual
       Current Value : 150
  14: Accuracy is not supported
  15: Motion Range is not supported
  16: Filter Option is not supported
  17: Confidence Threshold is not supported
  18: Emitter Enabled
       Description   : Emitter select, 0-disable all emitters, 1-enable laser, 2-enable laser auto (opt), 3-enable LED (opt)
       Current Value : 1
  19: Frames Queue Size
       Description   : Max number of frames you can hold at a given time. Increasing this number will reduce frame drops but increase latency, and vice versa
       Current Value : 16
  20: Total Frame Drops is not supported
  21: Auto Exposure Mode is not supported
  22: Power Line Frequency is not supported
  23: Asic Temperature is not supported
  24: Error Polling Enabled
       Description   : Enable / disable polling of camera internal errors
       Current Value : 1
  25: Projector Temperature is not supported
  26: Output Trigger Enabled
       Description   : Generate trigger from the camera to external device once per frame
       Current Value : 0
  27: Motion Module Temperature is not supported
  28: Depth Units
       Description   : Number of meters represented by a single depth unit
       Current Value : 0.001
  29: Enable Motion Correction is not supported
  30: Auto Exposure Priority is not supported
  31: Color Scheme is not supported
  32: Histogram Equalization Enabled is not supported
  33: Min Distance is not supported
  34: Max Distance is not supported
  35: Texture Source is not supported
  36: Filter Magnitude is not supported
  37: Filter Smooth Alpha is not supported
  38: Filter Smooth Delta is not supported
  39: Holes Fill is not supported
  40: Stereo Baseline
       Description   : Distance in mm between the stereo imagers
       Current Value : 49.8735
  41: Auto Exposure Converge Step is not supported
  42: Inter Cam Sync Mode
       Description   : Inter-camera synchronization mode: 0:Default, 1:Master, 2:Slave, 3:Full Salve, 4-258:Genlock with burst count of 1-255 frames for each trigger, 259 and 260 for two frames per trigger with laser ON-OFF and OFF-ON.
       Current Value : 0
  43: Stream Filter is not supported
  44: Stream Format Filter is not supported
  45: Stream Index Filter is not supported
  46: Emitter On Off
       Description   : Alternating emitter pattern, toggled on/off on per-frame basis
       Current Value : 0
  47: Zero Order Point X is not supported
  48: Zero Order Point Y is not supported
  49: LDD temperature is not supported
  50: Mc Temperature is not supported
  51: Ma Temperature is not supported
  52: Hardware Preset is not supported
  53: Global Time Enabled
       Description   : Enable/Disable global timestamp
       Current Value : 1
  54: Apd Temperature is not supported
  55: Enable Mapping is not supported
  56: Enable Relocalization is not supported
  57: Enable Pose Jumping is not supported
  58: Enable Dynamic Calibration is not supported
  59: Depth Offset is not supported
  60: Led Power is not supported
  61: Zero Order Enabled is not supported
  62: Enable Map Preservation is not supported
  63: Freefall Detection Enabled is not supported
  64: Receiver Gain is not supported
  65: Post Processing Sharpening is not supported
  66: Pre Processing Sharpening is not supported
  67: Noise Filtering is not supported
  68: Invalidation Bypass is not supported
  69: Digital Gain is not supported
  70: Sensor Mode is not supported
  71: Emitter Always On
       Description   : Emitter always on mode: 0:disabled(default), 1:enabled
       Current Value : 0
  72: Thermal Compensation is not supported
  73: Trigger Camera Accuracy Health is not supported
  74: Reset Camera Accuracy Health is not supported
  75: Host Performance is not supported
  76: Hdr Enabled
       Description   : HDR Option
       Current Value : 0
  77: Sequence Name
       Description   : HDR Option
       Current Value : 0
  78: Sequence Size
       Description   : HDR Option
       Current Value : 2
  79: Sequence Id
       Description   : HDR Option
       Current Value : 0
  80: Humidity Temperature is not supported
  81: Enable Max Usable Range is not supported
  82: Alternate IR is not supported
  83: Noise Estimation is not supported
  84: Enable IR Reflectivity is not supported
  85: Auto Exposure Limit
       Description   : Exposure limit is in microseconds. Default is 0 which means full exposure range. If the requested exposure limit is greater than frame time, it will be set to frame time at runtime. Setting will not take effect until next streaming session.
       Current Value : 5000
  86: Auto Gain Limit
       Description   : Gain limits ranges from 16 to 248. Default is 0 which means full gain. If the requested gain limit is less than 16, it will be set to 16. If the requested gain limit is greater than 248, it will be set to 248. Setting will not take effect until next streaming session.
       Current Value : 248
  87: Auto Rx Sensitivity is not supported
  88: Transmitter Frequency is not supported
  89: Vertical Binning is not supported
  90: Receiver Sensitivity is not supported
  91: Auto Exposure Limit Toggle
       Description   : Toggle Auto-Exposure Limit
       Current Value : 1
  92: Auto Gain Limit Toggle
       Description   : Toggle Auto-Gain Limit
       Current Value : 0
Sensor supports the following options:

  0: Backlight Compensation
       Description   : Enable / disable backlight compensation
       Current Value : 0
  1: Brightness
       Description   : UVC image brightness
       Current Value : 0
  2: Contrast
       Description   : UVC image contrast
       Current Value : 50
  3: Exposure
       Description   : Controls exposure time of color camera. Setting any value will disable auto exposure
       Current Value : 100
  4: Gain
       Description   : UVC image gain
       Current Value : 64
  5: Gamma
       Description   : UVC image gamma setting
       Current Value : 300
  6: Hue
       Description   : UVC image hue
       Current Value : 0
  7: Saturation
       Description   : UVC image saturation setting
       Current Value : 64
  8: Sharpness
       Description   : UVC image sharpness setting
       Current Value : 50
  9: White Balance
       Description   : Controls white balance of color image. Setting any value will disable auto white balance
       Current Value : 4600
  10: Enable Auto Exposure
       Description   : Enable / disable auto-exposure
       Current Value : 1
  11: Enable Auto White Balance
       Description   : Enable / disable auto-white-balance
       Current Value : 1
  12: Visual Preset is not supported
  13: Laser Power is not supported
  14: Accuracy is not supported
  15: Motion Range is not supported
  16: Filter Option is not supported
  17: Confidence Threshold is not supported
  18: Emitter Enabled is not supported
  19: Frames Queue Size
       Description   : Max number of frames you can hold at a given time. Increasing this number will reduce frame drops but increase latency, and vice versa
       Current Value : 16
  20: Total Frame Drops is not supported
  21: Auto Exposure Mode is not supported
  22: Power Line Frequency
       Description   : Power Line Frequency
       Current Value : 3
  23: Asic Temperature is not supported
  24: Error Polling Enabled is not supported
  25: Projector Temperature is not supported
  26: Output Trigger Enabled is not supported
  27: Motion Module Temperature is not supported
  28: Depth Units is not supported
  29: Enable Motion Correction is not supported
  30: Auto Exposure Priority
       Description   : Restrict Auto-Exposure to enforce constant FPS rate. Turn ON to remove the restrictions (may result in FPS drop)
       Current Value : 0
  31: Color Scheme is not supported
  32: Histogram Equalization Enabled is not supported
  33: Min Distance is not supported
  34: Max Distance is not supported
  35: Texture Source is not supported
  36: Filter Magnitude is not supported
  37: Filter Smooth Alpha is not supported
  38: Filter Smooth Delta is not supported
  39: Holes Fill is not supported
  40: Stereo Baseline is not supported
  41: Auto Exposure Converge Step is not supported
  42: Inter Cam Sync Mode is not supported
  43: Stream Filter is not supported
  44: Stream Format Filter is not supported
  45: Stream Index Filter is not supported
  46: Emitter On Off is not supported
  47: Zero Order Point X is not supported
  48: Zero Order Point Y is not supported
  49: LDD temperature is not supported
  50: Mc Temperature is not supported
  51: Ma Temperature is not supported
  52: Hardware Preset is not supported
  53: Global Time Enabled
       Description   : Enable/Disable global timestamp
       Current Value : 1
  54: Apd Temperature is not supported
  55: Enable Mapping is not supported
  56: Enable Relocalization is not supported
  57: Enable Pose Jumping is not supported
  58: Enable Dynamic Calibration is not supported
  59: Depth Offset is not supported
  60: Led Power is not supported
  61: Zero Order Enabled is not supported
  62: Enable Map Preservation is not supported
  63: Freefall Detection Enabled is not supported
  64: Receiver Gain is not supported
  65: Post Processing Sharpening is not supported
  66: Pre Processing Sharpening is not supported
  67: Noise Filtering is not supported
  68: Invalidation Bypass is not supported
  69: Digital Gain is not supported
  70: Sensor Mode is not supported
  71: Emitter Always On is not supported
  72: Thermal Compensation is not supported
  73: Trigger Camera Accuracy Health is not supported
  74: Reset Camera Accuracy Health is not supported
  75: Host Performance is not supported
  76: Hdr Enabled is not supported
  77: Sequence Name is not supported
  78: Sequence Size is not supported
  79: Sequence Id is not supported
  80: Humidity Temperature is not supported
  81: Enable Max Usable Range is not supported
  82: Alternate IR is not supported
  83: Noise Estimation is not supported
  84: Enable IR Reflectivity is not supported
  85: Auto Exposure Limit is not supported
  86: Auto Gain Limit is not supported
  87: Auto Rx Sensitivity is not supported
  88: Transmitter Frequency is not supported
  89: Vertical Binning is not supported
  90: Receiver Sensitivity is not supported
  91: Auto Exposure Limit Toggle is not supported
  92: Auto Gain Limit Toggle is not supported
Sensor supports the following options:

  0: Backlight Compensation is not supported
  1: Brightness is not supported
  2: Contrast is not supported
  3: Exposure is not supported
  4: Gain is not supported
  5: Gamma is not supported
  6: Hue is not supported
  7: Saturation is not supported
  8: Sharpness is not supported
  9: White Balance is not supported
  10: Enable Auto Exposure is not supported
  11: Enable Auto White Balance is not supported
  12: Visual Preset is not supported
  13: Laser Power is not supported
  14: Accuracy is not supported
  15: Motion Range is not supported
  16: Filter Option is not supported
  17: Confidence Threshold is not supported
  18: Emitter Enabled is not supported
  19: Frames Queue Size
       Description   : Max number of frames you can hold at a given time. Increasing this number will reduce frame drops but increase latency, and vice versa
       Current Value : 16
  20: Total Frame Drops is not supported
  21: Auto Exposure Mode is not supported
  22: Power Line Frequency is not supported
  23: Asic Temperature is not supported
  24: Error Polling Enabled is not supported
  25: Projector Temperature is not supported
  26: Output Trigger Enabled is not supported
  27: Motion Module Temperature is not supported
  28: Depth Units is not supported
  29: Enable Motion Correction
       Description   : Enable/Disable Automatic Motion Data Correction
       Current Value : 1
  30: Auto Exposure Priority is not supported
  31: Color Scheme is not supported
  32: Histogram Equalization Enabled is not supported
  33: Min Distance is not supported
  34: Max Distance is not supported
  35: Texture Source is not supported
  36: Filter Magnitude is not supported
  37: Filter Smooth Alpha is not supported
  38: Filter Smooth Delta is not supported
  39: Holes Fill is not supported
  40: Stereo Baseline is not supported
  41: Auto Exposure Converge Step is not supported
  42: Inter Cam Sync Mode is not supported
  43: Stream Filter is not supported
  44: Stream Format Filter is not supported
  45: Stream Index Filter is not supported
  46: Emitter On Off is not supported
  47: Zero Order Point X is not supported
  48: Zero Order Point Y is not supported
  49: LDD temperature is not supported
  50: Mc Temperature is not supported
  51: Ma Temperature is not supported
  52: Hardware Preset is not supported
  53: Global Time Enabled
       Description   : Enable/Disable global timestamp
       Current Value : 1
  54: Apd Temperature is not supported
  55: Enable Mapping is not supported
  56: Enable Relocalization is not supported
  57: Enable Pose Jumping is not supported
  58: Enable Dynamic Calibration is not supported
  59: Depth Offset is not supported
  60: Led Power is not supported
  61: Zero Order Enabled is not supported
  62: Enable Map Preservation is not supported
  63: Freefall Detection Enabled is not supported
  64: Receiver Gain is not supported
  65: Post Processing Sharpening is not supported
  66: Pre Processing Sharpening is not supported
  67: Noise Filtering is not supported
  68: Invalidation Bypass is not supported
  69: Digital Gain is not supported
  70: Sensor Mode is not supported
  71: Emitter Always On is not supported
  72: Thermal Compensation is not supported
  73: Trigger Camera Accuracy Health is not supported
  74: Reset Camera Accuracy Health is not supported
  75: Host Performance is not supported
  76: Hdr Enabled is not supported
  77: Sequence Name is not supported
  78: Sequence Size is not supported
  79: Sequence Id is not supported
  80: Humidity Temperature is not supported
  81: Enable Max Usable Range is not supported
  82: Alternate IR is not supported
  83: Noise Estimation is not supported
  84: Enable IR Reflectivity is not supported
  85: Auto Exposure Limit is not supported
  86: Auto Gain Limit is not supported
  87: Auto Rx Sensitivity is not supported
  88: Transmitter Frequency is not supported
  89: Vertical Binning is not supported
  90: Receiver Sensitivity is not supported
  91: Auto Exposure Limit Toggle is not supported
  92: Auto Gain Limit Toggle is not supported
[New Thread 0x7fffe2c49700 (LWP 1390)]
[New Thread 0x7fffe2448700 (LWP 1391)]
[Thread 0x7fffe2448700 (LWP 1391) exited]
[New Thread 0x7fffe2448700 (LWP 1392)]
[Thread 0x7fffe2448700 (LWP 1392) exited]
[New Thread 0x7fffe2448700 (LWP 1393)]
[New Thread 0x7fffe1c47700 (LWP 1394)]
[Thread 0x7fffe1c47700 (LWP 1394) exited]
[New Thread 0x7fffe1c47700 (LWP 1395)]
[New Thread 0x7fffe1446700 (LWP 1396)]
[New Thread 0x7fffe0c45700 (LWP 1397)]
[New Thread 0x7fffe0444700 (LWP 1398)]
[New Thread 0x7fffdfc43700 (LWP 1399)]
[New Thread 0x7fffdf442700 (LWP 1400)]
[New Thread 0x7fffdec41700 (LWP 1401)]
[New Thread 0x7fffde440700 (LWP 1402)]
[New Thread 0x7fffddb11700 (LWP 1403)]
[New Thread 0x7fffdd0b4700 (LWP 1404)]
[New Thread 0x7fffdc8b3700 (LWP 1405)]
[New Thread 0x7fffd7fff700 (LWP 1406)]
[New Thread 0x7fffd77fe700 (LWP 1407)]
[New Thread 0x7fffd6ffd700 (LWP 1408)]
[New Thread 0x7fffd67fc700 (LWP 1409)]
[New Thread 0x7fffd5ffb700 (LWP 1410)]
[Thread 0x7fffd67fc700 (LWP 1409) exited]
[Thread 0x7fffd5ffb700 (LWP 1410) exited]
[Thread 0x7fffddb11700 (LWP 1403) exited]
[Thread 0x7fffdd0b4700 (LWP 1404) exited]
[Thread 0x7fffdc8b3700 (LWP 1405) exited]
[Thread 0x7fffd77fe700 (LWP 1407) exited]
[Thread 0x7fffd7fff700 (LWP 1406) exited]
[Thread 0x7fffd6ffd700 (LWP 1408) exited]
[New Thread 0x7fffd6ffd700 (LWP 1411)]
[New Thread 0x7fffd7fff700 (LWP 1412)]
[New Thread 0x7fffd77fe700 (LWP 1413)]
[New Thread 0x7fffdc8b3700 (LWP 1414)]
[New Thread 0x7fffddc3f700 (LWP 1415)]
[New Thread 0x7fffdd43e700 (LWP 1416)]
[New Thread 0x7fffd67fc700 (LWP 1417)]
[New Thread 0x7fffd5ffb700 (LWP 1418)]
Tbc = 
0.999971, -0.0015239, 0.00745183, -0.0208106
0.00151524, 0.999998, 0.00116696, 0.00516718
-0.0074536, -0.00115564, 0.999972, 0.0116547
 fx = 604.76
 fy = 604.005
 cx = 322.166
 cy = 244.154
 height = 480
 width = 640
 Coeff = 0, 0, 0, 0, 0, 
 Model = Inverse Brown Conrady

ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: RGB-D-Inertial
Loading settings from /dpds/ORB_SLAM3/Examples/RGB-D-Inertial/RealSense_D435i.yaml
Camera1.k3 optional parameter does not exist...
	-Loaded camera 1
Camera.newHeight optional parameter does not exist...
Camera.newWidth optional parameter does not exist...
	-Loaded image info
	-Loaded IMU calibration
	-Loaded RGB-D calibration
	-Loaded ORB settings
Viewer.imageViewScale optional parameter does not exist...
	-Loaded viewer settings
System.LoadAtlasFromFile optional parameter does not exist...
System.SaveAtlasToFile optional parameter does not exist...
	-Loaded Atlas settings
System.thFarPoints optional parameter does not exist...
	-Loaded misc parameters
----------------------------------
SLAM settings: 
	-Camera 1 parameters (Pinhole): [ 617.201 617.362 324.637 242.462 ]
	-Camera 1 distortion parameters: [  0 0 0 0 ]
	-Original image size: [ 640 , 480 ]
	-Current image size: [ 640 , 480 ]
	-Sequence FPS: 30
	-Gyro noise: 0.01
	-Accelerometer noise: 0.1
	-Gyro walk: 1e-06
	-Accelerometer walk: 0.0001
	-IMU frequency: 200
	-RGB-D depth map factor: 1000
	-Features per image: 1250
	-ORB scale factor: 1.2
	-ORB number of scales: 8
	-Initial FAST threshold: 20
	-Min FAST threshold: 7


Loading ORB Vocabulary. This could take a while...

Thread 1 "rgbd_inertial_r" received signal SIGILL, Illegal instruction.
0x00007ffff239b588 in DBoW2::FORB::fromString(cv::Mat&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /dpds/ORB_SLAM3/Thirdparty/DBoW2/lib/libDBoW2.so
(gdb) 
(gdb) backtrace
#0  0x00007ffff239b588 in DBoW2::FORB::fromString(cv::Mat&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () at /dpds/ORB_SLAM3/Thirdparty/DBoW2/lib/libDBoW2.so
#1  0x00007ffff797b109 in DBoW2::TemplatedVocabulary<cv::Mat, DBoW2::FORB>::loadFromTextFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    at /dpds/ORB_SLAM3/lib/libORB_SLAM3.so
#2  0x00007ffff796b58d in ORB_SLAM3::System::System(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ORB_SLAM3::System::eSensor, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () at /dpds/ORB_SLAM3/lib/libORB_SLAM3.so
#3  0x000055555540cc71 in main ()
(gdb) 

more info please help........... :cactus:

**Comment by saadnec** [comment]
Did U solve it?

**Comment by saadnec** [comment]
> i managed to pass that:
> 
> root@r131-far-7b76474d46-xbcgl:/dpds/ORB_SLAM3/build/bin# ./tevel_slam ORBvoc.txt RealSense_D435i.yaml 2022/08/15 15:59:08.664750 [INFO] timeUtility::getCurrentMicro() USE ROS IS SET TO FALSE 2022/08/15 15:59:08.664795 [TRACE] GrpcAbstractDriver::GrpcAbstractDriver() 2022/08/15 15:59:08.664801 [TRACE] GrpcAbstractDriver::setThresholdToPrint(), sendingThreshold=80, grabbingThreshold=50 2022/08/15 15:59:08.665355 [INFO] FrontCameraDataInterface::FrontCameraDataInterface(), GOT DNS FROM ENVIRONMENT VARIABLE, [r131-front-camera-driver], IP=10.43.170.209 2022/08/15 15:59:08.665362 [INFO] FrontCameraDataInterface::FrontCameraDataInterface(), GOT PORT FROM ENVIRONMENT VARIABLE 3500 2022/08/15 15:59:08.665381 [TRACE] sharedMemoryHandler::sharedMemoryHandler(), UNIQUE IDENTIFIER- r131_frontCameraDriver, SIZE- 24, OWNER- false 2022/08/15 15:59:08.665389 [TRACE] sharedMemoryHandler::reInitSharedMemorySize(), UNIQUE IDENTIFIER- r131_frontCameraDriver, RESIZING TO=4301468 2022/08/15 15:59:08.665398 [TRACE] doubleBufferSMHandler::initAsSlave(), r131_frontCameraDriver, SUCCESSFULLY 2022/08/15 15:59:08.665942 [TRACE] sharedMemoryHandler::sharedMemoryHandler(), UNIQUE IDENTIFIER- r131_D435_GYRO, SIZE- 24, OWNER- false 2022/08/15 15:59:08.665947 [TRACE] sharedMemoryHandler::reInitSharedMemorySize(), UNIQUE IDENTIFIER- r131_D435_GYRO, RESIZING TO=238 2022/08/15 15:59:08.665952 [TRACE] doubleBufferSMHandler::initAsSlave(), r131_D435_GYRO, SUCCESSFULLY 2022/08/15 15:59:08.665957 [TRACE] sharedMemoryHandler::sharedMemoryHandler(), UNIQUE IDENTIFIER- r131_D435_ACCL, SIZE- 24, OWNER- false 2022/08/15 15:59:08.665960 [TRACE] sharedMemoryHandler::reInitSharedMemorySize(), UNIQUE IDENTIFIER- r131_D435_ACCL, RESIZING TO=238 2022/08/15 15:59:08.665965 [TRACE] doubleBufferSMHandler::initAsSlave(), r131_D435_ACCL, SUCCESSFULLY ORBvoc.txt RealSense_D435i.yaml
> 
> ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza. ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza. This program comes with ABSOLUTELY NO WARRANTY; This is free software, and you are welcome to redistribute it under certain conditions. See LICENSE.txt.
> ## Input sensor was set to: RGB-D-Inertial
> Loading settings from RealSense_D435i.yaml
> Camera1.k3 optional parameter does not exist...
> -Loaded camera 1
> Camera.newHeight optional parameter does not exist...
> Camera.newWidth optional parameter does not exist...
> -Loaded image info
> -Loaded IMU calibration
> -Loaded RGB-D calibration
> -Loaded ORB settings
> Viewer.imageViewScale optional parameter does not exist...
> -Loaded viewer settings
> System.LoadAtlasFromFile optional parameter does not exist...
> System.SaveAtlasToFile optional parameter does not exist...
> -Loaded Atlas settings
> System.thFarPoints optional parameter does not exist...
> -Loaded misc parameters
> 
> SLAM settings: -Camera 1 parameters (Pinhole): [ 617.201 617.362 324.637 242.462 ] -Camera 1 distortion parameters: [ 0 0 0 0 ] -Original image size: [ 640 , 480 ] -Current image size: [ 640 , 480 ] -Sequence FPS: 30 -Gyro noise: 0.01 -Accelerometer noise: 0.1 -Gyro walk: 1e-06 -Accelerometer walk: 0.0001 -IMU frequency: 200 -RGB-D depth map factor: 1000 -Features per image: 1250 -ORB scale factor: 1.2 -ORB number of scales: 8 -Initial FAST threshold: 20 -Min FAST threshold: 7
> 
> Loading ORB Vocabulary. This could take a while... Illegal instruction (core dumped)
> 
> now stuck on orb vocublary loading...

How did u end up passing it?

**Comment by naren-research** [comment]
Hi. I am also getting an illegal instruction error with ORBSLAM2. What should I do get past this error? 

#0  0x0000555555605ef6 in DBoW2::TemplatedVocabulary<cv::Mat, DBoW2::FORB>::loadFromBinaryFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#1  0x00005555555f94e5 in ORB_SLAM2::System::System(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ORB_SLAM2::System::eSensor, bool, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()

Any help will be appreciated! Thanks

**Comment by amsjntz** [comment]
Have any of you ever found the problem?
